name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and start services with Docker Compose
        run: |
          docker-compose up --build -d redis-api

      - name: Wait for the app to be ready
        run: |
          until curl -f http://localhost:8000/healthcheck; do echo waiting for API; sleep 5; done

      - name: Run unit tests
        run: |
          docker-compose up unit-tests

      - name: Run integration tests
        run: |
          docker-compose up integration-tests

      - name: Tear down Docker Compose
        run: |
          docker-compose down
