name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis-api:
        image: redis-api:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl -f http://localhost:8000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system

      # Run unit tests
      - name: Run unit tests
        run: |
          pytest -v tests/unit

      - name: Set up Docker Compose
        run: |
          docker-compose up --build -d

      # Wait for the FastAPI app to be healthy
      - name: Wait for the FastAPI service to be ready
        run: |
          docker-compose exec redis-api bash -c "until curl -f http://localhost:8000/healthcheck; do sleep 5; done"

      # Run integration tests
      - name: Run integration tests
        run: |
          pytest -v tests/integration

      - name: Tear down Docker Compose
        run: |
          docker-compose down
